### ISSUE TITLE
[BUG]: Object has no attribute 'ap'

### ISSUE THREAD

**Issue by Tigrex-Dai** [Hanschase/BreminderPlugin#1]
![image](https://github.com/user-attachments/assets/f7a5cdf1-5512-4592-a092-0e4623cca9c5)

**Comment by Hanschase** [comment]
这个问题我之前也遇到过，但是提高插件优先级之后问题就解决了，你可以先尝试将报错代码注释掉，并不影响插件的使用

**Comment by Tigrex-Dai** [comment]
ah确实可用，谢谢！
